name: Feature request
description: Request a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to propose enhancements to Developer Experience tooling, docs, or workflows.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the pain point and who it affects.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should we solve it? Include alternatives considered.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Affected areas, risks, and expected outcomes.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: This is a feature/enhancement request (not a question or doc issue)
          required: true
