name: Working group update
description: Request an update to a Working Group page or metadata
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to our project.

  - type: textarea
    id: which
    attributes:
      label: Which
      description: Which Working Group needs or wants this update?
      placeholder: |
        Give context and describe the problem, challenge or opportunity you see
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What
      description: What is this update roughly about?
      placeholder: |
        For example describe a change in members, a change in lead member,
        new meeting minutes, links, or metadata.
    validations:
      required: true
